-- VoidArchive Supabase Initialization Script (Fixed)
-- Run this in your Supabase SQL Editor

-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    subject TEXT,
    slide_count INTEGER DEFAULT 0,
    dominant_color TEXT DEFAULT '#6750A4',
    time_spent TEXT,
    teaser TEXT,
    creation_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    word_count INTEGER DEFAULT 0
);

-- 2. Create Ratings Table
CREATE TABLE IF NOT EXISTS public.hardware_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT REFERENCES public.projects(id) ON DELETE CASCADE,
    identity_hash TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    telemetry JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(project_id, identity_hash)
);

-- 3. Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hardware_ratings ENABLE ROW LEVEL SECURITY;

-- 4. Set Policies
-- Project Reading (Public)
CREATE POLICY "Allow public read access to projects" ON public.projects
    FOR SELECT USING (true);

-- Rating Management (Anonymous)
-- Allow anyone to Insert a new rating
CREATE POLICY "Allow anonymous insert for ratings" ON public.hardware_ratings
    FOR INSERT WITH CHECK (true);

-- Allow anyone to Update their existing rating (based on identity_hash)
CREATE POLICY "Allow anonymous update for ratings" ON public.hardware_ratings
    FOR UPDATE USING (true) WITH CHECK (true);

-- 5. Storage Bucket (Dashboard Action Required)
-- Create a bucket named 'void-archive' and set it to PUBLIC.
